This is makeindex, version 2.17 [TeX Live 2024] (kpathsea + Thai support).
Scanning style file ./report_SSME.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file report_SSME.acn....done (21 entries accepted, 0 rejected).
Sorting entries....done (110 comparisons).
Generating output file report_SSME.acr....done (32 lines written, 0 warnings).
Output written in report_SSME.acr.
Transcript written in report_SSME.alg.
